Fix for Android 14 + update some dependencies
nfcgate/nfcgate pull request #140
Opened 2023-11-10 18:07 UTC by weebl2000

No clue if this is wanted, but my Android Studio was warning me a lot and this seems to work.

2024-01-27 23:29 UTC, roussosalex commented
Thanks for contributing (again)! Could you please rebase this PR on the updated `v2` branch?

2024-01-28 19:30 UTC, weebl2000 commented
> Thanks for contributing (again)! Could you please rebase this PR on the updated `v2` branch?

Sure, I've reapplied the suggestions on the latest v2 branch.

2024-01-29 01:04 UTC, roussosalex requested changes
Much needed update to AndroidX. Thanks!

2024-01-29 01:04 UTC, roussosalex commented on app/src/main/assets/html/desfire-info.en.html
> +</html>
Fixing newlines and quotes should be in a separate PR

2024-01-29 01:23 UTC, weebl2000 commented on app/src/main/assets/html/desfire-info.en.html
> +</html>
Done, removed any files that only have newlines added and reverted all lines that only had quotation marks changed.

2024-01-29 01:25 UTC, roussosalex approved these changes

2024-01-29 19:17 UTC, kleest approved these changes

2024-01-30 01:13 UTC, merged